baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "reveal-hugo"
plugins = [
    "Simplemenu",
]

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
custom_theme = "robot-lung.css"
margin = 0.2
transition = "slide"
transition_speed = "fast"
