baseURL = "https://portfolio.jackgreenberg.co"
languageCode = "en-us"
title = "Jack Greenberg | Portfolio"
theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
custom_theme = "robot-lung.css"
margin = 0.2
transition = "slide"
transition_speed = "fast"

[[params.reveal_hugo.plugins]]
name = "Simplemenu"
source = "simplemenu/simplemenu.js"
